 export const blogData = [
    {
      "id": 4,
      "title": "AI is revolutionizing drug discovery with Dr. Julia Moore",
      "image": "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Sam Whitfield",
      "authorPic": "author2.jpg",
      "published_date": "October 10, 2023",
      "reading_time": "6 minutes",
      "content": "In this episode, we dive into the world of AI in healthcare with Dr. Julia Moore, discussing how AI is speeding up the process of drug discovery...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 5,
      "title": "The future of mental health apps with Professor Ethan Wright",
      "image": "https://images.pexels.com/photos/356079/pexels-photo-356079.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Olivia Grant",
      "authorPic": "author3.jpg",
      "published_date": "September 29, 2023",
      "reading_time": "7 minutes",
      "content": "Mental health apps are becoming more advanced and accessible. We talk to Professor Ethan Wright about the latest innovations in this space...",
      "tags": ["Mental Health", "Tech"]
    },
    {
      "id": 6,
      "title": "Improving remote patient monitoring with wearable sensors",
      "image": "https://images.pexels.com/photos/5083222/pexels-photo-5083222.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "Health",
      "author": "Megan Reese",
      "authorPic": "author4.jpg",
      "published_date": "October 3, 2023",
      "reading_time": "5 minutes",
      "content": "Wearable sensors are making it easier to monitor patients remotely, allowing for better healthcare management...",
      "tags": ["Wearable Tech", "Health"]
    },
    {
      "id": 7,
      "title": "Gene editing: What the future holds with Dr. Emily Watson",
      "image": "https://images.pexels.com/photos/2280549/pexels-photo-2280549.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Biotech",
      "author": "Alex Turner",
      "authorPic": "author5.jpg",
      "published_date": "October 6, 2023",
      "reading_time": "9 minutes",
      "content": "Gene editing is one of the most promising fields in biotechnology. Dr. Emily Watson shares her insights on its future...",
      "tags": ["Biotech", "Health"]
    },
    {
      "id": 8,
      "title": "Wearable technology and its impact on fitness",
      "image": "https://images.pexels.com/photos/1000082/pexels-photo-1000082.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Fitness",
      "author": "Ryan Harris",
      "authorPic": "author6.jpg",
      "published_date": "October 2, 2023",
      "reading_time": "4 minutes",
      "content": "Fitness trackers and smartwatches are changing the way we monitor and maintain our health. We take a closer look at the latest innovations...",
      "tags": ["Wearable Tech", "Fitness"]
    },
    {
      "id": 9,
      "title": "How robotics are transforming surgeries",
      "image": "https://images.pexels.com/photos/3844581/pexels-photo-3844581.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Tech",
      "author": "Sophie Lee",
      "authorPic": "author7.jpg",
      "published_date": "September 25, 2023",
      "reading_time": "8 minutes",
      "content": "Robotic-assisted surgeries are increasing in precision and reducing recovery times for patients. Here’s what you need to know...",
      "tags": ["Tech", "Health"]
    },
    {
      "id": 10,
      "title": "Developments in nanotechnology for cancer treatment",
      "image": "https://images.pexels.com/photos/416184/pexels-photo-416184.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "David Clarke",
      "authorPic": "author8.jpg",
      "published_date": "October 8, 2023",
      "reading_time": "10 minutes",
      "content": "Nanotechnology has the potential to revolutionize cancer treatment. We explore the latest advancements in this field...",
      "tags": ["Health", "Biotech"]
    },
    {
      "id": 11,
      "title": "Telemedicine: The future of healthcare?",
      "image": "https://images.pexels.com/photos/3055662/pexels-photo-3055662.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Emma Collins",
      "authorPic": "author9.jpg",
      "published_date": "September 28, 2023",
      "reading_time": "5 minutes",
      "content": "Telemedicine is growing rapidly, offering new ways for patients to access healthcare remotely. But is it the future of healthcare?",
      "tags": ["Tech", "Health"]
    },
    {
      "id": 12,
      "title": "The role of AI in diagnosing rare diseases",
      "image": "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "AI",
      "author": "James Anderson",
      "authorPic": "author10.jpg",
      "published_date": "October 12, 2023",
      "reading_time": "7 minutes",
      "content": "AI is being used to detect and diagnose rare diseases earlier than ever before. We speak with leading researchers in this space...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 13,
      "title": "How sleep tracking wearables are improving our health",
      "image": "https://images.pexels.com/photos/965117/pexels-photo-965117.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Sarah Walker",
      "authorPic": "author11.jpg",
      "published_date": "October 1, 2023",
      "reading_time": "6 minutes",
      "content": "Sleep tracking has become more advanced with wearables. We discuss how these devices are helping us sleep better...",
      "tags": ["Wearable Tech", "Health"]
    },
    {
      "id": 41,
      "title": "AI is revolutionizing drug discovery with Dr. Julia Moore",
      "image": "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Sam Whitfield",
      "authorPic": "author2.jpg",
      "published_date": "October 10, 2023",
      "reading_time": "6 minutes",
      "content": "In this episode, we dive into the world of AI in healthcare with Dr. Julia Moore, discussing how AI is speeding up the process of drug discovery...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 51,
      "title": "The future of mental health apps with Professor Ethan Wright",
      "image": "https://images.pexels.com/photos/356079/pexels-photo-356079.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Olivia Grant",
      "authorPic": "author3.jpg",
      "published_date": "September 29, 2023",
      "reading_time": "7 minutes",
      "content": "Mental health apps are becoming more advanced and accessible. We talk to Professor Ethan Wright about the latest innovations in this space...",
      "tags": ["Mental Health", "Tech"]
    },
    {
      "id": 61,
      "title": "Improving remote patient monitoring with wearable sensors",
      "image": "https://images.pexels.com/photos/5083222/pexels-photo-5083222.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "Health",
      "author": "Megan Reese",
      "authorPic": "author4.jpg",
      "published_date": "October 3, 2023",
      "reading_time": "5 minutes",
      "content": "Wearable sensors are making it easier to monitor patients remotely, allowing for better healthcare management...",
      "tags": ["Wearable Tech", "Health"]
    },
    {
      "id": 71,
      "title": "Gene editing: What the future holds with Dr. Emily Watson",
      "image": "https://images.pexels.com/photos/2280549/pexels-photo-2280549.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Biotech",
      "author": "Alex Turner",
      "authorPic": "author5.jpg",
      "published_date": "October 6, 2023",
      "reading_time": "9 minutes",
      "content": "Gene editing is one of the most promising fields in biotechnology. Dr. Emily Watson shares her insights on its future...",
      "tags": ["Biotech", "Health"]
    },
    {
      "id": 81,
      "title": "Wearable technology and its impact on fitness",
      "image": "https://images.pexels.com/photos/1000082/pexels-photo-1000082.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Fitness",
      "author": "Ryan Harris",
      "authorPic": "author6.jpg",
      "published_date": "October 2, 2023",
      "reading_time": "4 minutes",
      "content": "Fitness trackers and smartwatches are changing the way we monitor and maintain our health. We take a closer look at the latest innovations...",
      "tags": ["Wearable Tech", "Fitness"]
    },
    {
      "id": 91,
      "title": "How robotics are transforming surgeries",
      "image": "https://images.pexels.com/photos/3844581/pexels-photo-3844581.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Tech",
      "author": "Sophie Lee",
      "authorPic": "author7.jpg",
      "published_date": "September 25, 2023",
      "reading_time": "8 minutes",
      "content": "Robotic-assisted surgeries are increasing in precision and reducing recovery times for patients. Here’s what you need to know...",
      "tags": ["Tech", "Health"]
    },
    {
      "id": 101,
      "title": "Developments in nanotechnology for cancer treatment",
      "image": "https://images.pexels.com/photos/416184/pexels-photo-416184.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "David Clarke",
      "authorPic": "author8.jpg",
      "published_date": "October 8, 2023",
      "reading_time": "10 minutes",
      "content": "Nanotechnology has the potential to revolutionize cancer treatment. We explore the latest advancements in this field...",
      "tags": ["Health", "Biotech"]
    },
    {
      "id": 111,
      "title": "Telemedicine: The future of healthcare?",
      "image": "https://images.pexels.com/photos/3055662/pexels-photo-3055662.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Emma Collins",
      "authorPic": "author9.jpg",
      "published_date": "September 28, 2023",
      "reading_time": "5 minutes",
      "content": "Telemedicine is growing rapidly, offering new ways for patients to access healthcare remotely. But is it the future of healthcare?",
      "tags": ["Tech", "Health"]
    },
    {
      "id": 121,
      "title": "The role of AI in diagnosing rare diseases",
      "image": "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "AI",
      "author": "James Anderson",
      "authorPic": "author10.jpg",
      "published_date": "October 12, 2023",
      "reading_time": "7 minutes",
      "content": "AI is being used to detect and diagnose rare diseases earlier than ever before. We speak with leading researchers in this space...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 131,
      "title": "How sleep tracking wearables are improving our health",
      "image": "https://images.pexels.com/photos/965117/pexels-photo-965117.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Sarah Walker",
      "authorPic": "author11.jpg",
      "published_date": "October 1, 2023",
      "reading_time": "6 minutes",
      "content": "Sleep tracking has become more advanced with wearables. We discuss how these devices are helping us sleep better...",
      "tags": ["Wearable Tech", "Health"]
    },
    {
      "id": 141,
      "title": "AI in personalized nutrition: A deep dive with Dr. Alice Green",
      "image": "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Health",
      "author": "Matthew Baker",
      "authorPic": "author12.jpg",
      "published_date": "October 14, 2023",
      "reading_time": "7 minutes",
      "content": "AI is shaping the future of personalized nutrition. Dr. Alice Green shares her insights into how algorithms are helping us eat smarter...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 151,
      "title": "The impact of AI on surgical precision with Dr. Mark Hughes",
      "image": "https://images.pexels.com/photos/709860/pexels-photo-709860.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Tech",
      "author": "Laura Simmons",
      "authorPic": "author13.jpg",
      "published_date": "October 11, 2023",
      "reading_time": "8 minutes",
      "content": "Dr. Mark Hughes discusses how AI-driven tools are enhancing precision in the operating room...",
      "tags": ["AI", "Health", "Tech"]
    },
    {
      "id": 161,
      "title": "Gene therapy breakthroughs: Interview with Dr. Chloe Stevens",
      "image": "https://images.pexels.com/photos/11532475/pexels-photo-11532475.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "Biotech",
      "author": "Nathaniel Brooks",
      "authorPic": "author14.jpg",
      "published_date": "October 17, 2023",
      "reading_time": "10 minutes",
      "content": "Dr. Chloe Stevens shares the latest breakthroughs in gene therapy and what the future holds...",
      "tags": ["Biotech", "Health"]
    },
    {
      "id": 171,
      "title": "Smart pills: The next step in health monitoring?",
      "image": "https://images.pexels.com/photos/2994531/pexels-photo-2994531.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Tech",
      "author": "Emily Dawson",
      "authorPic": "author15.jpg",
      "published_date": "October 9, 2023",
      "reading_time": "6 minutes",
      "content": "Smart pills could soon monitor health from the inside. We explore the latest innovations in this field...",
      "tags": ["Tech", "Health"]
    },
    {
      "id": 181,
      "title": "The rise of AI-powered prosthetics with Dr. Adam Lane",
      "image": "https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "AI",
      "author": "Olivia Harper",
      "authorPic": "author16.jpg",
      "published_date": "October 5, 2023",
      "reading_time": "9 minutes",
      "content": "AI-powered prosthetics are transforming the lives of amputees. Dr. Adam Lane discusses the latest advancements...",
      "tags": ["AI", "Tech"]
    },
    {
      "id": 191,
      "title": "Virtual reality for mental health therapy",
      "image": "https://images.pexels.com/photos/2398355/pexels-photo-2398355.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Samantha Collins",
      "authorPic": "author17.jpg",
      "published_date": "October 3, 2023",
      "reading_time": "5 minutes",
      "content": "Virtual reality is becoming a powerful tool for mental health therapy. We take a closer look...",
      "tags": ["Mental Health", "Tech"]
    },
    {
      "id": 201,
      "title": "How AI is predicting epidemics with Dr. Maria Holmes",
      "image": "https://images.pexels.com/photos/17485678/pexels-photo-17485678/free-photo-of-an-artist-s-illustration-of-artificial-intelligence-ai-this-image-depicts-how-ai-could-be-used-in-the-field-of-sustainability-from-biodiversity-to-climate-it-was-created-by-nidia-dias.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "Health",
      "author": "John Taylor",
      "authorPic": "author18.jpg",
      "published_date": "October 7, 2023",
      "reading_time": "8 minutes",
      "content": "AI is being used to predict and prevent future epidemics. Dr. Maria Holmes explains the technology behind it...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 211,
      "title": "3D-printed organs: Hype or reality?",
      "image": "https://images.pexels.com/photos/941572/pexels-photo-941572.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Biotech",
      "author": "Michael Roberts",
      "authorPic": "author19.jpg",
      "published_date": "October 4, 2023",
      "reading_time": "9 minutes",
      "content": "3D printing is revolutionizing medicine. We explore the potential of printing organs for transplants...",
      "tags": ["Biotech", "Tech"]
    },
    {
      "id": 221,
      "title": "AI in sports: Enhancing athletic performance",
      "image": "https://images.pexels.com/photos/2527394/pexels-photo-2527394.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Sports",
      "author": "Hannah Smith",
      "authorPic": "author20.jpg",
      "published_date": "October 6, 2023",
      "reading_time": "6 minutes",
      "content": "AI is making its mark in the sports industry. From performance tracking to injury prevention, the possibilities are endless...",
      "tags": ["AI", "Sports"]
    },
    {
      "id": 231,
      "title": "CRISPR: The next frontier in genetic engineering",
      "image": "https://images.pexels.com/photos/3735789/pexels-photo-3735789.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Biotech",
      "author": "Brian Davis",
      "authorPic": "author21.jpg",
      "published_date": "October 16, 2023",
      "reading_time": "10 minutes",
      "content": "CRISPR technology is advancing rapidly, offering unprecedented control over genetic engineering...",
      "tags": ["Biotech", "Health"]
    },
    {
      "id": 241,
      "title": "How AI is helping doctors diagnose patients faster",
      "image": "https://images.pexels.com/photos/8439072/pexels-photo-8439072.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "AI",
      "author": "Jessica Adams",
      "authorPic": "author22.jpg",
      "published_date": "October 8, 2023",
      "reading_time": "7 minutes",
      "content": "AI is transforming the speed at which doctors can diagnose patients. We take a look at the tools behind this transformation...",
      "tags": ["AI", "Health"]
    },
    {
      "id": 251,
      "title": "AI-powered fitness apps: What's next?",
      "image": "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Fitness",
      "author": "David Cooper",
      "authorPic": "author23.jpg",
      "published_date": "October 12, 2023",
      "reading_time": "6 minutes",
      "content": "AI is powering the next generation of fitness apps. From personalized training to injury prevention, here’s what to expect...",
      "tags": ["Fitness", "AI"]
    },
    {
      "id": 261,
      "title": "The role of AI in early cancer detection",
      "image": "https://images.pexels.com/photos/7659570/pexels-photo-7659570.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "category": "Health",
      "author": "Sophia Brooks",
      "authorPic": "author24.jpg",
      "published_date": "October 18, 2023",
      "reading_time": "9 minutes",
      "content": "AI is playing a crucial role in the early detection of cancer. We explore how it’s being used in healthcare systems around the world...",
      "tags": ["AI", "Health"]
    },

    {
      "id": 201,
      "title": "Breaking the Stigma: Mental Health in the Workplace",
      "image": "https://images.pexels.com/photos/3184407/pexels-photo-3184407.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "John Martin",
      "authorPic": "author15.jpg",
      "published_date": "October 18, 2023",
      "reading_time": "6 minutes",
      "content": "Addressing mental health in the workplace is essential for creating a supportive environment. We explore strategies for breaking the stigma.",
      "tags": ["Mental Health", "Workplace"]
    },
    {
      "id": 202,
      "title": "Mental Health Apps: Tools for Personal Growth",
      "image": "https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Ella Gray",
      "authorPic": "author16.jpg",
      "published_date": "October 19, 2023",
      "reading_time": "7 minutes",
      "content": "Mental health apps are evolving to provide personalized support and therapy. Here’s how they can help you manage stress, anxiety, and more.",
      "tags": ["Mental Health", "Apps", "Technology"]
    },
    {
      "id": 203,
      "title": "The Impact of Nutrition on Mental Health",
      "image": "https://images.pexels.com/photos/414905/pexels-photo-414905.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Lucy Green",
      "authorPic": "author17.jpg",
      "published_date": "October 17, 2023",
      "reading_time": "8 minutes",
      "content": "The food we eat can affect our mood and mental health. Discover how proper nutrition is essential for maintaining emotional balance.",
      "tags": ["Mental Health", "Nutrition"]
    },
    {
      "id": 204,
      "title": "Coping with Stress in a Fast-Paced World",
      "image": "https://images.pexels.com/photos/1181739/pexels-photo-1181739.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "David Adams",
      "authorPic": "author18.jpg",
      "published_date": "October 13, 2023",
      "reading_time": "9 minutes",
      "content": "In today's fast-paced world, stress has become a common issue. Learn effective coping mechanisms to reduce its impact on your mental health.",
      "tags": ["Mental Health", "Stress"]
    },
    {
      "id": 205,
      "title": "How Exercise Boosts Mental Health",
      "image": "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Rachel White",
      "authorPic": "author19.jpg",
      "published_date": "October 11, 2023",
      "reading_time": "6 minutes",
      "content": "Regular physical activity has been shown to reduce anxiety and improve overall mental health. Here’s how exercise plays a crucial role in well-being.",
      "tags": ["Mental Health", "Exercise", "Fitness"]
    },
    {
      "id": 206,
      "title": "Meditation: A Powerful Tool for Mental Clarity",
      "image": "https://images.pexels.com/photos/3759654/pexels-photo-3759654.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Olivia Brown",
      "authorPic": "author20.jpg",
      "published_date": "October 16, 2023",
      "reading_time": "10 minutes",
      "content": "Meditation offers numerous mental health benefits, from reducing stress to improving focus. Learn how to integrate this practice into your daily routine.",
      "tags": ["Mental Health", "Meditation"]
    },
    {
      "id": 207,
      "title": "Therapy in the Digital Age: Virtual Counseling",
      "image": "https://images.pexels.com/photos/6863087/pexels-photo-6863087.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Sophia Turner",
      "authorPic": "author21.jpg",
      "published_date": "October 20, 2023",
      "reading_time": "7 minutes",
      "content": "With advancements in technology, virtual therapy is becoming a popular option for mental health care. We explore the benefits and challenges.",
      "tags": ["Mental Health", "Therapy", "Technology"]
    },
    {
      "id": 208,
      "title": "The Role of Support Networks in Mental Health",
      "image": "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Liam Scott",
      "authorPic": "author22.jpg",
      "published_date": "October 14, 2023",
      "reading_time": "8 minutes",
      "content": "Building strong support networks is essential for mental well-being. We discuss how friends, family, and communities play a vital role in emotional health.",
      "tags": ["Mental Health", "Support"]
    },
    {
      "id": 209,
      "title": "Understanding Depression and Its Symptoms",
      "image": "https://images.pexels.com/photos/1468371/pexels-photo-1468371.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Emma Williams",
      "authorPic": "author23.jpg",
      "published_date": "October 21, 2023",
      "reading_time": "9 minutes",
      "content": "Depression is a complex condition that affects millions. Learn about the common symptoms and treatment options available for managing depression.",
      "tags": ["Mental Health", "Depression"]
    },
    {
      "id": 210,
      "title": "Managing Mental Health During Life Transitions",
      "image": "https://images.pexels.com/photos/443944/pexels-photo-443944.jpeg?auto=compress&cs=tinysrgb&w=800",
      "category": "Mental Health",
      "author": "Noah Edwards",
      "authorPic": "author24.jpg",
      "published_date": "October 22, 2023",
      "reading_time": "6 minutes",
      "content": "Life transitions such as job changes, moving, or starting a family can impact mental health. Here are strategies to navigate these transitions.",
      "tags": ["Mental Health", "Life Transitions"]
    }
  ]
  